# Generated by Django 4.2.1 on 2023-08-15 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0004_rename_usernname_patient_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.IntegerField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('doctor', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
    ]
