# Generated by Django 4.2.1 on 2023-09-08 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='message',
        ),
    ]
